# Generated by Django 4.0.5 on 2022-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='countp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
