# Generated by Django 4.0.5 on 2022-07-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_details_countp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
