# Generated by Django 4.0.5 on 2022-07-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
