# Generated by Django 4.0.6 on 2022-08-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_tracking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='final_price',
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
