# Generated by Django 4.0.6 on 2022-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_order_details_final_price_order_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
