# Generated by Django 4.0.5 on 2022-07-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcf', '0002_alter_menu_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='lep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
