# Generated by Django 4.0.5 on 2022-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='image')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=11)),
                ('discripion', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
