# Generated by Django 4.0.5 on 2022-07-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gor', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gat', to='products.category'),
        ),
    ]
