# Generated by Django 4.0.5 on 2022-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_categ_alter_product_category1'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
