# Generated by Django 4.0.5 on 2022-07-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_opinion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
