# Generated by Django 4.0.5 on 2022-07-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_pic_alter_product_pic1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
