# Generated by Django 4.0.5 on 2022-07-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='last_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='discount',
        ),
    ]
