# Generated by Django 4.0.5 on 2022-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='proda',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
