# Generated by Django 4.0.5 on 2022-07-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_cent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
