# Generated by Django 4.0.5 on 2022-07-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_opinion_proda'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
